### ISSUE TITLE
Analysis couldn't run 

### ISSUE THREAD

**Issue by fereshteh2012** [rclab-auth/gidopensees#71] opened 2019-02-08 14:11 UTC
Dear gid opensees interface team,

when I perform analysis, I encounter a problem, saying that: could not run the analysis, please check generated tcl file.
I work with the latest gid version 14.0.1 and interface version 2.6.0 and I delete the problemtypes/opensees folder to install interface again but it doesn't work.
any help appreciated...
thanks.

**Comment by vpapanik** [comment] 2019-02-08 14:18
It happens to me as well lately, something has changed in windows maybe. We are looking upon the issue.

**Comment by fereshteh2012** [comment] 2019-02-08 14:19
this is my zip file

**Comment by fereshteh2012** [comment] 2019-02-08 14:24
I want to run but I couldn't , could you please tell me what should I do?

**Comment by vpapanik** [comment] 2019-02-08 14:26
The analysis runs ok, you just ignore the error and then run postprocess manually. We are looking on a fix.

**Comment by fereshteh2012** [comment] 2019-02-08 15:13
sorry my file doesn't attach here.

**Comment by fereshteh2012** [comment] 2019-02-09 08:38
Hi,
I want to attach my file but it doesn't work, do you know how I can attach it?

**Comment by fereshteh2012** [comment] 2019-02-09 09:20
r

**Comment by fereshteh2012** [comment] 2019-02-09 19:00
Hi,
May I ask you ta look my model, I tried to run but it doesn't work and failed.
thanks, 
[tokyoo3.gid.zip](https://github.com/rclab-auth/gidopensees/files/2848142/tokyoo3.gid.zip)

**Comment by fereshteh2012** [comment] 2019-02-09 19:01
Hi,
May I ask you ta look my model, I tried to run but it doesn't work and failed.
thanks,
[tokyo3.gid.zip](https://github.com/rclab-auth/gidopensees/files/2848147/tokyo3.gid.zip)

**Comment by Maffy92** [comment] 2019-04-14 23:58
I get the same aerror, Analysis could not run. even for a s imple model. If i proceed to post processing, it says model has not run to view results. Could you please help with this?

**Comment by vpapanik** [comment] 2019-11-14 20:55
The issue is fixed in the upcoming version 2.7.0, please wait a few days until it is released.

**Comment by Al-Haaj** [comment] 2020-01-03 14:53
@vpapanik Dear Sir Could you tell me when are you going to release version 2.7.0.
This error impedes my research progress. I hope you release it very soon and thanks for all team members for your efforts..

**Comment by ritamgc** [comment] 2020-01-11 18:52
@vpapanik Hi! I'm having the same problem. How can I run postprocess manually?

**Comment by vpapanik** [comment] 2020-01-13 22:00
New version 2.7.0 is coming really soon

**Closed by vpapanik** 2020-01-13 22:00 UTC

**Comment by Yahya-bit** [comment] 2020-02-24 21:58
> New version 2.7.0 is coming really soon

hello
sir i use gid14.1.8 and 2.7 but  the problem for analysis has crashed in gid opensees
pleas help me to slove it

**Comment by Israr777** [comment] 2021-02-01 13:28
Sir can you please guide me hoe to get  license for GID 2.8.0

**Comment by Israr777** [comment] 2021-02-01 13:30
Sir i am getting error on while clicking for analysis which appears that Analysis has crashed can you help me please i have been stuck for so long over this issue or uide me if it is due to Academic license
Thank you

**Comment by Yahya-bit** [comment] 2021-04-24 21:20
Sorry for late replay did you solve your problem?  Sent from Mail for Windows 10 From: Israr777Sent: Monday, February 1, 2021 3:30 PMTo: rclab-auth/gidopenseesCc: Yahya-bit; CommentSubject: Re: [rclab-auth/gidopensees] Analysis couldn't run (#71) Sir i am getting error on while clicking for analysis which appears that Analysis has crashed can you help me please i have been stuck for so long over this issue or uide me if it is due to Academic licenseThank you—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

	
        
		Virus-free. www.avg.com
